# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

import logging
import uuid
import os
from langchain_core.messages import AIMessage
from langgraph.graph.state import CompiledStateGraph
from langgraph.prebuilt import create_react_agent
from langgraph_supervisor import create_supervisor
from ioa_observe.sdk.decorators import agent, graph

from common.llm import get_llm
from graph.tools import VMManageAgent2Tool

from farm.card import AGENT_CARD

logger = logging.getLogger("intersight.supervisor.graph")

PROMPT1 = """You are a dual-purpose supervisor agent.

Your behavior is strictly rule-based and must follow this logic:

1. If the user prompt includes anything about Cisco Intersight server profiles, domain profiles, policies, 
   or API queries:
   - Route the task to worker agent 'intersight_query_worker'
   - Use the associated tool 'intersight_api_tool'
   - Do not attempt to answer or describe Intersight topics yourself.

2. If the user prompt is NOT about Intersight (server profiles, domain profiles, policies, or API queries):
   - Answer the question yourself.
   - Provide the best possible explanation, reasoning, or solution using your knowledge.
   - Be clear, detailed, and helpful in your response.

3. If the worker agent returns control and the result is successful with no errors:
   - Return an empty response and end the conversation.

4. If the worker agent returns an error:
   - Return the same error message verbatim.

In short:
- Cisco Intersight queries → must be routed only.  
- All other queries → you must answer fully and provide the best possible response."""

SUPERVISOR_PROMPT = """
You are a Supervisor Agent.
Your behavior is strictly rule-based and must follow this logic:

1. If the user prompt is about Virtual Machines (VM creations):
   - Route the task to the worker agent 'virtual_machine_agent'.
   - Do not attempt to answer the query yourself.

2. If the user prompt is NOT about Virtual Machines:
   - Do not answer it yourself.
   - Return the message: "This supervisor only supports Virtual Machine management."

3. If the worker agent returns control and the result is successful with no errors:
   - Return an empty response and end the conversation.

4. If the worker agent returns an error:
   - Return the same error message verbatim.
"""

@agent(name="exchange_agent")
class ExchangeGraph:
    def __init__(self):
        self.graph = self.build_graph()

    @graph(name="exchange_graph")
    def build_graph(self) -> CompiledStateGraph:
        """
        Constructs and compiles a LangGraph instance.

        This function initializes a `SupervisorAgent` to create the base graph structure
        and uses an `InMemorySaver` as the checkpointer for the compilation process.

        The resulting compiled graph can be used to execute Supervisor workflow in LangGraph Studio.

        Returns:
        CompiledGraph: A fully compiled LangGraph instance ready for execution.
        """
        model = get_llm()
        logger.debug(f"Model is : {model}")

        intersight_virtual_machine_agent = VMManageAgent2Tool(
            remote_agent_card=AGENT_CARD,
        )
        
        intersight_a2a_agent = create_react_agent(
            model=model,
            tools=[intersight_virtual_machine_agent],  # list of tools for the agent
            name="virtual_machine_agent",
        )
        logger.debug(f"Printing the supervisor prompt: {SUPERVISOR_PROMPT}")
        graph = create_supervisor(
            model=model,
            agents=[intersight_a2a_agent],  # worker agents list
            prompt=SUPERVISOR_PROMPT,
            add_handoff_back_messages=False,
            output_mode="last_message",
        ).compile()
        logger.debug("LangGraph supervisor created and compiled successfully.")
        return graph

    async def serve(self, prompt: str):
        """
        Processes the input prompt and returns a response from the graph.
        Args:
            prompt (str): The input prompt to be processed by the graph.
        Returns:
            str: The response generated by the graph based on the input prompt.
        """
        logger.debug("Entering serve method.")
        try:
            logger.debug("Entering serve method.")
            # build graph if not already built
            self.graph = self.build_graph()
            if not hasattr(self, 'graph'):
                logger.debug("Graph not found, building graph.")
                self.graph = self.build_graph()
            logger.debug(f"Received prompt: {prompt}")
            if not isinstance(prompt, str) or not prompt.strip():
                raise ValueError("Prompt must be a non-empty string.")
            # session_start()
            result = await self.graph.ainvoke({
                "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
                ],
            }, {"configurable": {"thread_id": uuid.uuid4()}})

            messages = result.get("messages", [])
            if not messages:
                raise RuntimeError("No messages found in the graph response.")

            # Find the last AIMessage with non-empty content
            for message in reversed(messages):
                if isinstance(message, AIMessage) and message.content.strip():
                    logger.debug(f"Valid AIMessage found: {message.content.strip()}")
                    return message.content.strip()

            raise RuntimeError("No valid AIMessage found in the graph response.")
        except ValueError as ve:
            logger.error(f"ValueError in serve method: {ve}")
            raise ValueError(str(ve))
        except Exception as e:
            logger.error(f"Error in serve method: {e}")
            raise Exception(str(e))
