# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

import logging
import uuid
import os
from langchain_core.messages import AIMessage
from langgraph.graph.state import CompiledStateGraph
from langgraph.prebuilt import create_react_agent
from langgraph_supervisor import create_supervisor
from ioa_observe.sdk.decorators import agent, graph

from common.llm import get_llm
from graph.tools import VMManageAgent2Tool

from farm.card import AGENT_CARD

logger = logging.getLogger("intersight.supervisor.graph")

SUPERVISOR_PROMPT = """
You are a Supervisor Agent.

Your responsibilities:
1. Engage with the user in natural conversation and provide general answers when the query is not related to Virtual Machine creation.
2. If the user explicitly requests to **create a Virtual Machine** (e.g., mentions provisioning, launching, or setting up a VM), do not answer the request yourself. 
   - Instead, forward the task to the worker agent: "virtual_machine_agent".
   - Do not provide details or explanations about the VM creation process yourself.

Rules:
- General, non-VM questions → respond conversationally and helpfully as the Supervisor.
- VM creation requests → route only, never answer.
- Be polite, concise, and consistent in your responses.
"""

@agent(name="exchange_agent")
class ExchangeGraph:
    def __init__(self):
        logger.info("Initiating the build graph")
        self.graph = self.build_graph()

    @graph(name="exchange_graph")
    def build_graph(self) -> CompiledStateGraph:
        """
        Constructs and compiles a LangGraph instance.

        This function initializes a `SupervisorAgent` to create the base graph structure
        and uses an `InMemorySaver` as the checkpointer for the compilation process.

        The resulting compiled graph can be used to execute Supervisor workflow in LangGraph Studio.

        Returns:
        CompiledGraph: A fully compiled LangGraph instance ready for execution.
        """
        model = get_llm()
        logger.debug(f"Model is : {model}")

        intersight_virtual_machine_agent = VMManageAgent2Tool(
            remote_agent_card=AGENT_CARD,
        )
        
        intersight_a2a_agent = create_react_agent(
            model=model,
            tools=[intersight_virtual_machine_agent],  # list of tools for the agent
            name="virtual_machine_agent",
        )
        logger.debug(f"Printing the supervisor prompt: {SUPERVISOR_PROMPT}")
        graph_builder = create_supervisor(
            model=model,
            agents=[intersight_a2a_agent],  # worker agents list
            prompt=SUPERVISOR_PROMPT,
            add_handoff_back_messages=False,
            output_mode="last_message",
        )
        compiled_graph = graph_builder.compile()
        logger.debug("LangGraph supervisor created and compiled successfully.")
        # mermaid_str = draw_mermaid(graph_builder)
        # logger.debug("Graph structure in Mermaid:\n" + mermaid_str)
        return compiled_graph

    async def serve(self, prompt: str):
        """
        Processes the input prompt and returns a response from the graph.
        Args:
            prompt (str): The input prompt to be processed by the graph.
        Returns:
            str: The response generated by the graph based on the input prompt.
        """
        logger.debug("Entering serve method.")
        try:
            logger.debug("Entering serve method.")
            # build graph if not already built
            self.graph = self.build_graph()
            if not hasattr(self, 'graph'):
                logger.debug("Graph not found, building graph.")
                self.graph = self.build_graph()
            logger.debug(f"Received prompt: {prompt}")
            if not isinstance(prompt, str) or not prompt.strip():
                raise ValueError("Prompt must be a non-empty string.")
            # session_start()
            result = await self.graph.ainvoke({
                "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
                ],
            }, {"configurable": {"thread_id": uuid.uuid4()}})

            messages = result.get("messages", [])
            if not messages:
                raise RuntimeError("No messages found in the graph response.")

            # Find the last AIMessage with non-empty content
            for message in reversed(messages):
                if isinstance(message, AIMessage) and message.content.strip():
                    logger.debug(f"Valid AIMessage found: {message.content.strip()}")
                    return message.content.strip()

            raise RuntimeError("No valid AIMessage found in the graph response.")
        except ValueError as ve:
            logger.error(f"ValueError in serve method: {ve}")
            raise ValueError(str(ve))
        except Exception as e:
            logger.error(f"Error in serve method: {e}")
            raise Exception(str(e))
